<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Fip_education extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Fip_education_model');
    } 

    /*
     * Listing of fip_education
     */
    function index()
    {
        $data['fip_education'] = $this->Fip_education_model->get_all_fip_education();
        
        $data['_view'] = 'fip_education/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new fip_education
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'emp_id' => $this->input->post('emp_id'),
				'ssc_percentage' => $this->input->post('ssc_percentage'),
				'ssc_passing_year' => $this->input->post('ssc_passing_year'),
				'ssc_institute' => $this->input->post('ssc_institute'),
				'inter_percentage' => $this->input->post('inter_percentage'),
				'inter_passing_year' => $this->input->post('inter_passing_year'),
				'inter_institute' => $this->input->post('inter_institute'),
				'ug_percentage' => $this->input->post('ug_percentage'),
				'ug_passing_year' => $this->input->post('ug_passing_year'),
				'ug_institute' => $this->input->post('ug_institute'),
				'pg_percentage' => $this->input->post('pg_percentage'),
				'pg_passing_year' => $this->input->post('pg_passing_year'),
				'pg_institute' => $this->input->post('pg_institute'),
				'phd_year' => $this->input->post('phd_year'),
				'phd_institute' => $this->input->post('phd_institute'),
            );
            
            $fip_education_id = $this->Fip_education_model->add_fip_education($params);
            redirect('fip_education/index');
        }
        else
        {            
            $data['_view'] = 'fip_education/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a fip_education
     */
    function edit($id)
    {   
        // check if the fip_education exists before trying to edit it
        $data['fip_education'] = $this->Fip_education_model->get_fip_education($id);
        
        if(isset($data['fip_education']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'emp_id' => $this->input->post('emp_id'),
					'ssc_percentage' => $this->input->post('ssc_percentage'),
					'ssc_passing_year' => $this->input->post('ssc_passing_year'),
					'ssc_institute' => $this->input->post('ssc_institute'),
					'inter_percentage' => $this->input->post('inter_percentage'),
					'inter_passing_year' => $this->input->post('inter_passing_year'),
					'inter_institute' => $this->input->post('inter_institute'),
					'ug_percentage' => $this->input->post('ug_percentage'),
					'ug_passing_year' => $this->input->post('ug_passing_year'),
					'ug_institute' => $this->input->post('ug_institute'),
					'pg_percentage' => $this->input->post('pg_percentage'),
					'pg_passing_year' => $this->input->post('pg_passing_year'),
					'pg_institute' => $this->input->post('pg_institute'),
					'phd_year' => $this->input->post('phd_year'),
					'phd_institute' => $this->input->post('phd_institute'),
                );

                $this->Fip_education_model->update_fip_education($id,$params);            
                redirect('fip_education/index');
            }
            else
            {
                $data['_view'] = 'fip_education/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The fip_education you are trying to edit does not exist.');
    } 

    /*
     * Deleting fip_education
     */
    function remove($id)
    {
        $fip_education = $this->Fip_education_model->get_fip_education($id);

        // check if the fip_education exists before trying to delete it
        if(isset($fip_education['id']))
        {
            $this->Fip_education_model->delete_fip_education($id);
            redirect('fip_education/index');
        }
        else
            show_error('The fip_education you are trying to delete does not exist.');
    }
    
}
