<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Fip_profile extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Fip_profile_model');
    } 

    /*
     * Listing of fip_profile
     */
    function index()
    {
        $data['fip_profile'] = $this->Fip_profile_model->get_all_fip_profile();
        
        $data['_view'] = 'fip_profile/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new fip_profile
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'emp_id' => $this->input->post('emp_id'),
				'dept' => $this->input->post('dept'),
				'dob' => $this->input->post('dob'),
				'gender' => $this->input->post('gender'),
				'mobileno' => $this->input->post('mobileno'),
				'mailid' => $this->input->post('mailid'),
				'city' => $this->input->post('city'),
				'aadhar' => $this->input->post('aadhar'),
				'pan' => $this->input->post('pan'),
				'bank_name' => $this->input->post('bank_name'),
				'bank_accno' => $this->input->post('bank_accno'),
				'bank_ifsc' => $this->input->post('bank_ifsc'),
            );
            
            $fip_profile_id = $this->Fip_profile_model->add_fip_profile($params);
            redirect('fip_profile/index');
        }
        else
        {            
            $data['_view'] = 'fip_profile/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a fip_profile
     */
    function edit($id)
    {   
        // check if the fip_profile exists before trying to edit it
        $data['fip_profile'] = $this->Fip_profile_model->get_fip_profile($id);
        
        if(isset($data['fip_profile']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'emp_id' => $this->input->post('emp_id'),
					'dept' => $this->input->post('dept'),
					'dob' => $this->input->post('dob'),
					'gender' => $this->input->post('gender'),
					'mobileno' => $this->input->post('mobileno'),
					'mailid' => $this->input->post('mailid'),
					'city' => $this->input->post('city'),
					'aadhar' => $this->input->post('aadhar'),
					'pan' => $this->input->post('pan'),
					'bank_name' => $this->input->post('bank_name'),
					'bank_accno' => $this->input->post('bank_accno'),
					'bank_ifsc' => $this->input->post('bank_ifsc'),
                );

                $this->Fip_profile_model->update_fip_profile($id,$params);            
                redirect('fip_profile/index');
            }
            else
            {
                $data['_view'] = 'fip_profile/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The fip_profile you are trying to edit does not exist.');
    } 

    /*
     * Deleting fip_profile
     */
    function remove($id)
    {
        $fip_profile = $this->Fip_profile_model->get_fip_profile($id);

        // check if the fip_profile exists before trying to delete it
        if(isset($fip_profile['id']))
        {
            $this->Fip_profile_model->delete_fip_profile($id);
            redirect('fip_profile/index');
        }
        else
            show_error('The fip_profile you are trying to delete does not exist.');
    }
    
}
