<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Fip_hour extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Fip_hour_model');
    } 

    /*
     * Listing of fip_hours
     */
    function index()
    {
        $data['fip_hours'] = $this->Fip_hour_model->get_all_fip_hours();
        
        $data['_view'] = 'fip_hour/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new fip_hour
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'hours' => $this->input->post('hours'),
            );
            
            $fip_hour_id = $this->Fip_hour_model->add_fip_hour($params);
            redirect('fip_hour/index');
        }
        else
        {            
            $data['_view'] = 'fip_hour/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a fip_hour
     */
    function edit($id)
    {   
        // check if the fip_hour exists before trying to edit it
        $data['fip_hour'] = $this->Fip_hour_model->get_fip_hour($id);
        
        if(isset($data['fip_hour']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'hours' => $this->input->post('hours'),
                );

                $this->Fip_hour_model->update_fip_hour($id,$params);            
                redirect('fip_hour/index');
            }
            else
            {
                $data['_view'] = 'fip_hour/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The fip_hour you are trying to edit does not exist.');
    } 

    /*
     * Deleting fip_hour
     */
    function remove($id)
    {
        $fip_hour = $this->Fip_hour_model->get_fip_hour($id);

        // check if the fip_hour exists before trying to delete it
        if(isset($fip_hour['id']))
        {
            $this->Fip_hour_model->delete_fip_hour($id);
            redirect('fip_hour/index');
        }
        else
            show_error('The fip_hour you are trying to delete does not exist.');
    }
    
}
