<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Fip_assign_activity extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Fip_assign_activity_model');
    } 

    /*
     * Listing of fip_assign_activity
     */
    function index()
    {
        $data['fip_assign_activity'] = $this->Fip_assign_activity_model->get_all_fip_assign_activity();
        
        $data['_view'] = 'fip_assign_activity/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new fip_assign_activity
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'emp_id' => $this->input->post('emp_id'),
				'date' => $this->input->post('date'),
				'task_desc' => $this->input->post('task_desc'),
				'task_comp_date' => $this->input->post('task_comp_date'),
				'task_assigned_by' => $this->input->post('task_assigned_by'),
            );
            
            $fip_assign_activity_id = $this->Fip_assign_activity_model->add_fip_assign_activity($params);
            redirect('fip_assign_activity/index');
        }
        else
        {            
            $data['_view'] = 'fip_assign_activity/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a fip_assign_activity
     */
    function edit($id)
    {   
        // check if the fip_assign_activity exists before trying to edit it
        $data['fip_assign_activity'] = $this->Fip_assign_activity_model->get_fip_assign_activity($id);
        
        if(isset($data['fip_assign_activity']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'emp_id' => $this->input->post('emp_id'),
					'date' => $this->input->post('date'),
					'task_desc' => $this->input->post('task_desc'),
					'task_comp_date' => $this->input->post('task_comp_date'),
					'task_assigned_by' => $this->input->post('task_assigned_by'),
                );

                $this->Fip_assign_activity_model->update_fip_assign_activity($id,$params);            
                redirect('fip_assign_activity/index');
            }
            else
            {
                $data['_view'] = 'fip_assign_activity/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The fip_assign_activity you are trying to edit does not exist.');
    } 

    /*
     * Deleting fip_assign_activity
     */
    function remove($id)
    {
        $fip_assign_activity = $this->Fip_assign_activity_model->get_fip_assign_activity($id);

        // check if the fip_assign_activity exists before trying to delete it
        if(isset($fip_assign_activity['id']))
        {
            $this->Fip_assign_activity_model->delete_fip_assign_activity($id);
            redirect('fip_assign_activity/index');
        }
        else
            show_error('The fip_assign_activity you are trying to delete does not exist.');
    }
    
}
