<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Fip_role extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Fip_role_model');
    } 

    /*
     * Listing of fip_roles
     */
    function index()
    {
        $data['fip_roles'] = $this->Fip_role_model->get_all_fip_roles();
        
        $data['_view'] = 'fip_role/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new fip_role
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'role' => $this->input->post('role'),
            );
            
            $fip_role_id = $this->Fip_role_model->add_fip_role($params);
            redirect('fip_role/index');
        }
        else
        {            
            $data['_view'] = 'fip_role/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a fip_role
     */
    function edit($id)
    {   
        // check if the fip_role exists before trying to edit it
        $data['fip_role'] = $this->Fip_role_model->get_fip_role($id);
        
        if(isset($data['fip_role']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'role' => $this->input->post('role'),
                );

                $this->Fip_role_model->update_fip_role($id,$params);            
                redirect('fip_role/index');
            }
            else
            {
                $data['_view'] = 'fip_role/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The fip_role you are trying to edit does not exist.');
    } 

    /*
     * Deleting fip_role
     */
    function remove($id)
    {
        $fip_role = $this->Fip_role_model->get_fip_role($id);

        // check if the fip_role exists before trying to delete it
        if(isset($fip_role['id']))
        {
            $this->Fip_role_model->delete_fip_role($id);
            redirect('fip_role/index');
        }
        else
            show_error('The fip_role you are trying to delete does not exist.');
    }
    
}
