<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Fip_hour_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get fip_hour by id
     */
    function get_fip_hour($id)
    {
        return $this->db->get_where('fip_hours',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all fip_hours
     */
    function get_all_fip_hours()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('fip_hours')->result_array();
    }
        
    /*
     * function to add new fip_hour
     */
    function add_fip_hour($params)
    {
        $this->db->insert('fip_hours',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update fip_hour
     */
    function update_fip_hour($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('fip_hours',$params);
    }
    
    /*
     * function to delete fip_hour
     */
    function delete_fip_hour($id)
    {
        return $this->db->delete('fip_hours',array('id'=>$id));
    }
}
