<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Fip_profile_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get fip_profile by id
     */
    function get_fip_profile($id)
    {
        return $this->db->get_where('fip_profile',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all fip_profile
     */
    function get_all_fip_profile()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('fip_profile')->result_array();
    }
        
    /*
     * function to add new fip_profile
     */
    function add_fip_profile($params)
    {
        $this->db->insert('fip_profile',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update fip_profile
     */
    function update_fip_profile($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('fip_profile',$params);
    }
    
    /*
     * function to delete fip_profile
     */
    function delete_fip_profile($id)
    {
        return $this->db->delete('fip_profile',array('id'=>$id));
    }
}
