<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Fip_activity_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get fip_activity by id
     */
    function get_fip_activity($id)
    {
        return $this->db->get_where('fip_activity',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all fip_activity
     */
    function get_all_fip_activity()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('fip_activity')->result_array();
    }
        
    /*
     * function to add new fip_activity
     */
    function add_fip_activity($params)
    {
        $this->db->insert('fip_activity',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update fip_activity
     */
    function update_fip_activity($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('fip_activity',$params);
    }
    
    /*
     * function to delete fip_activity
     */
    function delete_fip_activity($id)
    {
        return $this->db->delete('fip_activity',array('id'=>$id));
    }
}
