<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Fip_dept_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get fip_dept by id
     */
    function get_fip_dept($id)
    {
        return $this->db->get_where('fip_dept',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all fip_dept
     */
    function get_all_fip_dept()
    {
        $this->db->order_by('id', 'asc');
        return $this->db->get('fip_dept')->result_array();
    }
        
    /*
     * function to add new fip_dept
     */
    function add_fip_dept($params)
    {
        $this->db->insert('fip_dept',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update fip_dept
     */
    function update_fip_dept($id,$params)
    {
        $this->db->where('id',$id);
        $params['updated_at'] = date("Y-m-d H:i:s");
        return $this->db->update('fip_dept',$params);
    }
    
    /*
     * function to delete fip_dept
     */
    function delete_fip_dept($id)
    {
        return $this->db->delete('fip_dept',array('id'=>$id));
    }
}
