<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Fip_education_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get fip_education by id
     */
    function get_fip_education($id)
    {
        return $this->db->get_where('fip_education',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all fip_education
     */
    function get_all_fip_education()
    {
        $this->db->where('deleted_at', null);
        $this->db->order_by('id', 'desc');
        return $this->db->get('fip_education')->result_array();
    }
        
    /*
     * function to add new fip_education
     */
    function add_fip_education($params)
    {
        $this->db->insert('fip_education',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update fip_education
     */
    function update_fip_education($id,$params)
    {
        $params['updated_at'] = date("Y-m-d H:i:s");
        $this->db->where('id',$id);
        return $this->db->update('fip_education',$params);
    }
    
    /*
     * function to delete fip_education
     */
    function delete_fip_education($id)
    {
        $this->db->where('id',$id);
        $params = [];
        $params['deleted_at'] = date("Y-m-d H:i:s");
        return $this->db->update('fip_profile',$params);
        // return $this->db->delete('fip_education',array('id'=>$id));
    }
}
