<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Fip_user_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get fip_user by emp_id
     */
    function get_fip_user($emp_id)
    {
        return $this->db->get_where('fip_users',array('emp_id'=>$emp_id))->row_array();
    }
        
    /*
     * Get all fip_users
     */
    function get_all_fip_users()
    {
        $this->db->where('u.deleted_at',NULL);
        $this->db->select('u.id,u.emp_id,u.password,r.role');
        $this->db->from('fip_users as u');
        $this->db->join('fip_roles as r','u.role = r.id','inner');
        return $this->db->get()->result_array();
    }
        
    /*
     * function to add new fip_user
     */
    function add_fip_user($params)
    {
        $this->db->insert('fip_users',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update fip_user
     */
    function update_fip_user($emp_id,$params)
    {
        $this->db->where('emp_id',$emp_id);
        return $this->db->update('fip_users',$params);
    }
    
    /*
     * function to delete fip_user
     */
    function delete_fip_user($emp_id)
    {
        $this->db->where('emp_id',$emp_id);
        $params = [];
        $params['deleted_at'] = date("Y-m-d H:i:s");
        return $this->db->update('fip_users',$params);
    }
}
