<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Fip_workhour_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get fip_workhour by id
     */
    function get_fip_workhour($id)
    {
        return $this->db->get_where('fip_workhours',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all fip_workhours
     */
    function get_all_fip_workhours()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('fip_workhours')->result_array();
    }
        
    /*
     * function to add new fip_workhour
     */
    function add_fip_workhour($params)
    {
        $this->db->insert('fip_workhours',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update fip_workhour
     */
    function update_fip_workhour($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('fip_workhours',$params);
    }
    
    /*
     * function to delete fip_workhour
     */
    function delete_fip_workhour($id)
    {
        return $this->db->delete('fip_workhours',array('id'=>$id));
    }
}
